name: Github Pages Deploy

on:
  push:
    branches:
      - "master"  # lors d'un push sur la branch master

jobs:
  build:
    runs-on: ubuntu-latest # build realisé sur la derniere version d'ubuntu

    strategy:
      matrix:
        node-version: [16.x] # utilisation de la derniere version 16 de node

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install and build
        run: npm install && npm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: build
